ci:
  autoupdate_commit_msg: 'build(deps): pre-commit autoupdate'
  autoupdate_branch: 'dev'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.28.6
    hooks:
    - id: check-github-workflows
  - repo: https://github.com/coatl-dev/hadolint-coatl
    rev: 2.12.0.3
    hooks:
      - id: hadolint
