name: publish

on:
  push:
    branches:
      - coatl
    paths:
      - .github/workflows/docker-build-push-multi-registry.yml
      - .github/workflows/publish.yml
      - Dockerfile

jobs:
  tagger:
    runs-on: blacksmith
    outputs:
      version: ${{ steps.tags.outputs.version }}
      major-minor: ${{ steps.tags.outputs.major-minor }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract version number
        id: tags
        run: |
          # Extract the Python version from the Dockerfile
          VERSION=$(grep 'ENV PYTHON_VERSION' Dockerfile | cut -d '=' -f 2)
          echo "VERSION=${VERSION}"
          # Trim the version to the first two segments (major.minor)
          MAJOR_MINOR=$(echo $VERSION | cut -d'.' -f1-2)
          echo "MAJOR_MINOR=${MAJOR_MINOR}"
          # Export the extracted version to GITHUB_OUTPUT
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "major-minor=${MAJOR_MINOR}" >> $GITHUB_OUTPUT

  build:
    needs: tagger
    uses: ./.github/workflows/docker-build-push-multi-registry.yml
    with:
      dockerhub-repo: coatldev/six
      dockerhub-username: ${{ vars.DOCKERHUB_USERNAME }}
      quay-repo: quay.io/coatldev/six
      quay-username: ${{ vars.QUAY_USERNAME }}
      metadata-tags: |
        type=raw,value=${{ needs.tagger.outputs.version }}
        type=raw,value=${{ needs.tagger.outputs.major-minor }}
        type=raw,value=latest,enable={{is_default_branch}}
    secrets:
      dockerhub-password: ${{ secrets.DOCKERHUB_TOKEN }}
      quay-password: ${{ secrets.QUAY_ROBOT_TOKEN }}
