name: publish

on:
  push:
    branches:
      - 'coatl'
    paths:
      - '.github/workflows/publish.yml'
      - 'Dockerfile'
  schedule:
    - cron: '30 1 * * 1,5'

jobs:
  publish:
    uses: coatl-dev/workflows/.github/workflows/docker-publish-multi-platform.yml@v4
    with:
      registry-image: coatldev/six
      metadata-tags: |
        type=raw,value=${{ needs.build.outputs.version }}
        type=raw,value=${{ needs.build.outputs.major_minor }}
        type=raw,value=latest,enable={{is_default_branch}}
      dockerhub-username: ${{ vars.DOCKERHUB_USERNAME }}
    secrets:
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
