name: publish

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Dockerfile subdirectory
        id: dockerfile
        run: echo "subdir=$(echo ${{ github.event.release.tag_name }} | cut -d '.' -f 1,2)" >> $GITHUB_OUTPUT

      - name: Read __VERSION__ file
        id: getversion
        run: echo "version=$(cat ${{ steps.dockerfile.outputs.subdir }}/__VERSION__)" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ${{ steps.dockerfile.outputs.subdir }}
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: |
            coatldev/six:${{ github.event.release.tag_name }}
            coatldev/six:${{ steps.dockerfile.outputs.subdir }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
